using System;
using VrcTwitchOscBridge.Models;
using VrcTwitchOscBridge.Services;

namespace VrcTwitchOscBridge.Tests;

internal static class TestTriggerRuleSnapshotBuilder
{
    private static readonly TriggerRuleSnapshot Default = new(
        Id: System.Guid.Empty,
        IsEnabled: true,
        Name: "TestRule",
        IsGlobalOverride: true,
        AvatarProfileId: System.Guid.Empty,
        AvatarProfileName: string.Empty,
        RequiredAvatarId: string.Empty,
        RequiredAvatarName: string.Empty,
        SupporterAvatarProfileId: System.Guid.Empty,
        SupporterAvatarId: string.Empty,
        SupporterAvatarName: string.Empty,
        BelongsToMasterAvatarProfile: false,
        TriggerType: TwitchTriggerType.Bits,
        ChannelPointRewardId: string.Empty,
        ChannelPointRewardTitle: string.Empty,
        ManagedRewardReadyColor: string.Empty,
        ManagedRewardCooldownColor: string.Empty,
        ChatCommandEnabled: false,
        ChatCommandText: string.Empty,
        ChatCommandPermission: ChatCommandPermission.Everyone,
        MinimumAmount: 1,
        AmountScaledDurationEnabled: false,
        AmountUnitsPerDuration: 1,
        SecondsPerAmountUnit: 1,
        BitsAmountUnitsPerDuration: 50,
        BitsSecondsPerAmountUnit: 1,
        SubscriptionsAmountUnitsPerDuration: 1,
        SubscriptionsSecondsPerAmountUnit: 1,
        SubscriptionTier1SecondsPerSub: 0,
        SubscriptionTier2SecondsPerSub: 0,
        SubscriptionTier3SecondsPerSub: 0,
        AddBitsToSwapTime: false,
        MaxAccumulatedDurationEnabled: false,
        MaxAccumulatedDurationSeconds: 0,
        ActionType: OscActionType.AvatarParameter,
        MovementDirection: PlayerMovementDirection.Forward,
        ParameterName: string.Empty,
        ParameterType: OscParameterType.Float,
        IntZeroDurationMode: IntZeroDurationMode.Fixed,
        ParameterValue: string.Empty,
        FloatValueMode: FloatValueMode.Decimal,
        FloatTransitionInSeconds: 0,
        FloatTransitionOutSeconds: 0,
        ResetValue: string.Empty,
        ActiveFloatBoostRewardEnabled: false,
        ActiveFloatBoostRewardId: string.Empty,
        ActiveFloatBoostRewardTitle: string.Empty,
        ActiveFloatBoostRewardDescription: string.Empty,
        ActiveFloatBoostRewardCost: 0,
        ActiveFloatBoostRewardCooldownSeconds: 0,
        ActiveFloatBoostRewardReadyColor: string.Empty,
        ActiveFloatBoostRewardCooldownColor: string.Empty,
        ActiveFloatBoostAddValue: string.Empty,
        ActiveFloatBoostMinimumValue: string.Empty,
        ActiveFloatBoostMaximumValue: string.Empty,
        SupporterFloatAddEnabled: false,
        SupporterFloatAddMinimumValue: string.Empty,
        SupporterFloatAddMaximumValue: string.Empty,
        SupporterFloatAddRanges: Array.Empty<SupporterFloatAddRangeSnapshot>(),
        AvatarChangeTargetId: string.Empty,
        AvatarChangeResetId: string.Empty,
        AvatarTargetName: string.Empty,
        ResetAvatarName: string.Empty,
        AvatarRouletAvatarIds: Array.Empty<string>(),
        AvatarRouletAvatarNames: Array.Empty<string>(),
        RangeMinimum: 0,
        RangeMaximum: 0,
        DurationSeconds: 0,
        CooldownSeconds: 0,
        UsesLinkedChannelPointReward: false,
        BotMessageCooldownSeconds: null,
        SharedRewardChoiceEnabled: false,
        SharedRewardChoiceNumber: 0,
        SharedRewardHelpText: string.Empty,
        UsesSharedNumberedOutfitReward: false,
        PostOutfitChoiceListToTwitchChat: false,
        SetTriggerRestoreMode: SetTriggerRestoreMode.ConfiguredOnly,
        SupporterKeywordText: string.Empty,
        BitsKeywordEnabled: false,
        SetTriggerActions: Array.Empty<SetTriggerActionSnapshot>(),
        SpecialRulePairingMode: SpecialRulePairingMode.HidePairedWhileActive,
        TemporarilyDisabledRuleIds: Array.Empty<System.Guid>(),
        BotMessageTemplate: string.Empty,
        Rule: null!);

    public static TriggerRuleSnapshot Build(
        TwitchTriggerType triggerType = TwitchTriggerType.Bits,
        bool amountScaledDurationEnabled = false,
        double durationSeconds = 0,
        int bitsAmountUnitsPerDuration = 50,
        int bitsSecondsPerAmountUnit = 1,
        int subscriptionTier1SecondsPerSub = 0,
        int subscriptionTier2SecondsPerSub = 0,
        int subscriptionTier3SecondsPerSub = 0,
        bool addBitsToSwapTime = false)
    {
        var realRule = new TriggerRule
        {
            TriggerType = triggerType,
            DurationSeconds = durationSeconds,
            AmountScaledDurationEnabled = amountScaledDurationEnabled,
            BitsAmountUnitsPerDuration = bitsAmountUnitsPerDuration,
            BitsSecondsPerAmountUnit = bitsSecondsPerAmountUnit,
            SubscriptionTier1SecondsPerSub = subscriptionTier1SecondsPerSub,
            SubscriptionTier2SecondsPerSub = subscriptionTier2SecondsPerSub,
            SubscriptionTier3SecondsPerSub = subscriptionTier3SecondsPerSub
        };
        return Default with
        {
            Id = System.Guid.NewGuid(),
            TriggerType = triggerType,
            AmountScaledDurationEnabled = amountScaledDurationEnabled,
            DurationSeconds = durationSeconds,
            BitsAmountUnitsPerDuration = bitsAmountUnitsPerDuration,
            BitsSecondsPerAmountUnit = bitsSecondsPerAmountUnit,
            SubscriptionTier1SecondsPerSub = subscriptionTier1SecondsPerSub,
            SubscriptionTier2SecondsPerSub = subscriptionTier2SecondsPerSub,
            SubscriptionTier3SecondsPerSub = subscriptionTier3SecondsPerSub,
            AddBitsToSwapTime = addBitsToSwapTime,
            Rule = realRule
        };
    }
}
